name: CI

on:
  push:
    branches:
      - main

jobs:
  continuos-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
      - name: Run install, build and test
        run: |
          npm install
          npm run build
          npm run test
        continue-on-error: true

      - name: Check test result
        if: ${{ failure() }}
        run: exit 1

      - name: Push if tests pass
        if: ${{ success() }}
        run: git push origin HEAD:main
